import NavBar from '@/components/navBar/NavBar';
import './globals.css';
import {Inter} from 'next/font/google';
import Footer from '@/components/footer/Footer';
import {ThemeProvider} from '@/contexts/ThemeContext';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider>
          <div className='container'>
            <NavBar />
            {children}
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
